# Generated by Django 5.1.6 on 2025-02-17 21:13

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admin_tools', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='SyncSession',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_time', models.DateTimeField(auto_now_add=True)),
                ('end_time', models.DateTimeField(null=True)),
                ('status', models.CharField(choices=[('running', 'Running'), ('completed', 'Completed'), ('failed', 'Failed')], max_length=20)),
                ('total_objects', models.IntegerField(default=0)),
                ('synced_objects', models.IntegerField(default=0)),
                ('failed_objects', models.IntegerField(default=0)),
            ],
            options={
                'verbose_name': 'Sync Session',
                'verbose_name_plural': 'Sync Sessions',
                'ordering': ['-start_time'],
            },
        ),
        migrations.CreateModel(
            name='SyncError',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('object_type', models.CharField(max_length=50)),
                ('object_id', models.CharField(blank=True, max_length=100, null=True)),
                ('error_message', models.TextField()),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='errors', to='admin_tools.syncsession')),
            ],
            options={
                'verbose_name': 'Sync Error',
                'verbose_name_plural': 'Sync Errors',
                'ordering': ['-timestamp'],
            },
        ),
    ]
